# Generated by Django 2.2.4 on 2020-10-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
