# Generated by Django 2.2.4 on 2020-10-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='Book',
        ),
        migrations.AddField(
            model_name='author',
            name='Book',
            field=models.ManyToManyField(related_name='authors', to='books_authors_app.Book'),
        ),
    ]
